### ISSUE TITLE
format error of jplace using read partition

### ISSUE THREAD

**Issue by 444thLiao** [matthiasblanke/App-SpaM#1]
When I analysis the jplace file generated by app-sam using large query sequences, it seems like that it wrongly merge "results from different read partition".

Because i will meet error like that using the `guppy`.

```
Uncaught exception: syntax error parsing between line 60024 character 2 and line 60024 character 3 of ./appsam_out/SRP142370/placed.jplace
Fatal error: exception Ppatteries.Sparse.Parse_error("syntax error parsing", _, _, _)
```

When i jump to that line, i found that it miss a comma like that.
![image](https://user-images.githubusercontent.com/16633223/104404740-57b70680-5596-11eb-9dae-e9d2891cd2be.png)

if I manual add it, it will be fine.

And furthermore, if we got more read partition, this error would come up at 120024 line. (I am not sure why not 120048, i guess that it might because you partition reads per 60000.)

**Comment by matthiasblanke** [comment]
Thanks for the hint, should be resolved now. There will also be a new bioconda version as soon as I am finished with some additional changes. You can also increase the partition size with `-b`. Let me know if you need it on bioconda immediately or run into any further problems.
