### ISSUE TITLE
internal node names

### ISSUE THREAD

**Issue by davised** [matthiasblanke/App-SpaM#3]
Hi Matthias,

Awesome software, it has a lot of potential.

I'm wondering, if keeping the original internal node names is not possible, would it be possible to write a mapping of the original node names to the renamed internal node names?

This will be helpful in our workflow, if so.

Thanks,

Ed

**Comment by matthiasblanke** [comment]
Hi Ed, 
this was already implemented, but commented out by me for some reason. 
If you compile the newest version, the supplied internal node names should now be retained in the output tree as well.
I'll try to update the conda package soon as well. 
If you have any further issues just let me know.
Best, Matthias

**Comment by davised** [comment]
Works great. Thanks for the quick response!
